### ISSUE TITLE
PUT /controls/stakeholder/{id} does not correctly save "stakeholderGroups" field

### ISSUE THREAD

**Issue by carlosthe19916** [konveyor/tackle-controls#66]
How to reproduce:
- Create a stakeholder and assign him at least one group. This can be done using `POST /controls/stakeholder`.
- Edit the previously created stakeholder and change the set of groups assigned before. This can be done using `PUT /controls/stakeholder/{id}`
- The new set of groups assigned to the stakeholder adds the new groups but doesn't delete the previous one.

Here is an example using the UI. In the following video we see a stakeholder with 3 groups and then, using the edit modal, I tried to have only 1 group instead of 3; see that even though the `PUT` call is correct the data is not updated in the backend.

https://user-images.githubusercontent.com/2582866/112292796-c056e980-8c91-11eb-86cb-7a83daf1d718.mp4

**Comment by mrizzi** [comment]
Thanks @carlosthe19916 for reporting this.
I think it's an effect of the same issue we discussed in the last days and already reported in #64 that prevents `stakeholder` `PUT` endpoint to work as expected.
