### ISSUE TITLE
Fix typo on TagType field

### ISSUE THREAD

**Issue by carlosthe19916** [konveyor/tackle-controls#92]
The current definition of the class `TagType` is something like:

```java
@Entity
@Table(name = "tag_type")
@SQLDelete(sql = "UPDATE tag_type SET deleted = true WHERE id = ?", check = ResultCheckStyle.COUNT)
@Where(clause = "deleted = false")
public class TagType extends AbstractEntity {
   
    @Filterable
    public String colour;
   
}
```

Shouldn't the field `colour` should be named `color`?
The location of the field mentioned is this one:

https://github.com/konveyor/tackle-controls/blob/cb386fe8ee1afac4ce12390a9ea2dd328576f9dd/src/main/java/io/tackle/controls/entities/TagType.java#L28

**Comment by mrizzi** [comment]
It's written in UK English (rather than in US English) so it's not a typo :wink:
